# Site settings
title: zakun 随手记
SEOTitle: zakun 随手记 | zakun Blog
header-img: img/big_banner/post-bg-desk.jpg
email: qzk80@gmail.com
description: "Every failure is leading towards success."
keyword: "zakun, blog, 博客, 随手记, php, mysql, nginx"
url: "http://zakun.github.io"          # your host, for absolute URL
baseurl: "/blog"      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zakun/blog.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Don't be pushed by your problems. Be led by your dreams."
sidebar-avatar: /blog/img/zakun.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings
RSS: true
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
github_username:    zakun
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 42d8113b72da2238320a                            #生成的clientID
  clientSecret: 7c44fe6b2e732e37ac2b4554f09821ec791e93ee    #生成的clientSecret
  repo: blog    #仓库名称
  owner: zakun    #github用户名
  admin: zakun
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-139110006-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
{
  title: "Jekyll",
  href: "https://jekyllrb.com/docs/structure"
},{
  title: "gitHub",
  href: "https://github.com/zakun"
}
]
